// flow-typed signature: 14b9a5de5abd36bb5c625a8fb1782ca8
// flow-typed version: <<STUB>>/redux-elm-middleware_v4.0.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-elm-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-elm-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-elm-middleware/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-elm-middleware/index' {
  declare module.exports: $Exports<'redux-elm-middleware'>;
}
declare module 'redux-elm-middleware/index.js' {
  declare module.exports: $Exports<'redux-elm-middleware'>;
}
declare module 'redux-elm-middleware/src/index.js' {
  declare module.exports: $Exports<'redux-elm-middleware/src/index'>;
}
